---
title: "Portfolio 2"
---

```{r load-packages, message=FALSE}
##install.packages("tidytuesdayR")
library(tidyverse)
tuesdata <- tidytuesdayR::tt_load('2023-10-10')
haunted_places <- tuesdata$haunted_places
```

I get the haunted houses dataset from the Tidy Tuesday Github (https://github.com/rfordatascience/tidytuesday/blob/main/data/2023/2023-10-10/readme.md). My research question in general is to see where are the haunted houses in the US! 

```{r NC haunted houses}
##first I want to know where are the haunted houses in North Carolina.
##I would filter the dataset into only houses in NC.
NC_haunted_places <- haunted_places %>% 
  filter(state == "North Carolina")
```
Now I know that there are `r nrow(NC_haunted_places)` haunted houses in North Caronlina, which is a litte scary. Now I wanted to know how they are located within North Caronlina. 

```{r location within NC}
##After taking a look at the dataset, I want to merge Winston-Salem to Winston because they refer to the same location. 
NC_haunted_places <- NC_haunted_places %>%
mutate(
  city = case_when(
    city == "Winston-Salem" ~ "Winston",
    TRUE ~ city
  ))
```


```{r visualization of haunted houses locations in NC}
haunted_counts_NC <- NC_haunted_places %>%
  count(city, name = "num_haunted_houses") %>% 
  arrange(desc(num_haunted_houses))
print(haunted_counts_NC)
##I also want to see a bar graph of which city has the most haunted houses.
ggplot(data = NC_haunted_places, aes(x = city)) +
  geom_bar() +
  coord_flip() +
  labs(x = "City", y = "Number of haunted houses")

##I want to see how these haunted houses are located within NC.
ggplot(NC_haunted_places, mapping = aes(
  x = longitude,
  y = latitude,
  color = state
)) +
  geom_point(alpha = .5) +
  labs(
    title= "North Carolina haunted houses Locations",
    x = "Longitude", 
    y = "Latitude"
    )
```