---
title: "Thesis data cleaning"
author: "Allison Li"
date: "03102025"
output: 
  html_document:
    encoding: UTF-8
    toc: true
    number_sections: false
    toc_float: true
    toc_depth: 4
    fig_caption: true
---

```{r load-packages, message=FALSE}
##install packages
##install.packages("ltm")
##install.packages("psych")
##install.packages("ppcor")
##For this portfolio, I would like to use the dataset from my thesis study.
library(psych)
library(haven)
library(ggplot2)
library(ltm)
library(ppcor)
library(tidyverse)
library(dplyr)
Thesis <- read_sav("~/Downloads/Thesis.sav")
```

## Step 1: clean data
```{r clean data}
##The first step is to clean data, and I started with getting rid of participants that did not finished the study, as well as deleting variable that does not have any data, such as recipient name.  
Thesis_clean <- Thesis %>% 
  select(-RecipientLastName, -RecipientFirstName, -RecipientEmail, -ExternalReference, -DistributionChannel, -browser_info_Resolution, -StartDate, -EndDate, -browser_info_Browser, -browser_info_Version, -IPAddress, -RecordedDate, -LocationLatitude, -LocationLongitude, -ResponseId, -UserLanguage, -browser_info_Operating_System, -robot_timer_First_Click, -robot_timer_Last_Click, -robot_timer_Page_Submit, -robot_timer_Click_Count)
Thesis_clean <- Thesis_clean[-c(1), ]
##Keep only participants with progress >= 50
Thesis_clean <- Thesis_clean %>% 
  filter(Progress >= 50)
##Remove people's answers who did not give consent to participate in the study
Thesis_clean <- Thesis_clean %>%
  filter(Consent1 != 2, (!is.na(difficulties)))
```

## Step 2: reverse coding the scales
```{r scoring scales}
##Define columns that should remain as text, which are my short-answer responses
text_cols <- c("BS_TL_CG_1", "BS_TL_CG_2", "BS_TL_CG_3", "BS_TL_CG_4", "BS_TL_CG_5", 
"BS_TL_Recycle_1", "BS_TL_Recycling_2", "BS_TL_Recycling_3", "BS_TL_Recycling_4", "BS_TL_Recycling_5", 
"BS_TL_Crime_1", "BS_TL_Crime_2", "BS_TL_Crime_3", "BS_TL_Crime_4", "BS_TL_Crime_5", 
"major", "BS_shortanswer1", "BS_shortanswer2", "comment") 

Thesis_clean <- Thesis_clean %>%
  mutate(across(-all_of(text_cols), ~ as.numeric(.)))

##Convert the numeric columns: 
##step I: I noticed that SPSS assigned the wrong value for the thought rating items, so I have to recoded the wrong value first before reverse-coding it
Thesis_scale <- Thesis_clean %>%
  mutate(
    across(c(BS_TR_CG_1, BS_TR_CG_2, BS_TR_CG_3, BS_TR_CG_4, BS_TR_CG_5, BS_TR_Recylcing_1, BS_TR_Recylcing_2, BS_TR_Recylcing_3,
             BS_TR_Recylcing_4, BS_TR_Recylcing_5, BS_TR_Crime_1, BS_TR_Crime_2, BS_TR_Crime_3, BS_TR_Crime_4, BS_TR_Crime_5), ~ recode(., 
             `4` = 0, `5` = 1, `6` = 2, `7` = 3, `8` = 4, `9` = 5, `10` = 6, `11` = 7, `12` = 8, `13` = 9, `14` = 10))
    )##Thought-Rating for the originally wrong value   
                                                                                                                      
##step II: 
Thesis_scale <- Thesis_scale %>%
  mutate(
    across(c(BPS_1, BPS_2, BPS_3, BPS_6, BPS_9, BPS_11), ~ recode(., 
      `1` = 5, `2` = 4, `4` = 2, `5` = 1)), ##Bullshit Propensity Scale
    
    across(c(BS_TR_CG_1, BS_TR_CG_2, BS_TR_CG_3, BS_TR_CG_4, BS_TR_CG_5, BS_TR_Recylcing_1, BS_TR_Recylcing_2, BS_TR_Recylcing_3, BS_TR_Recylcing_4, BS_TR_Recylcing_5, BS_TR_Crime_1, BS_TR_Crime_2, BS_TR_Crime_3, BS_TR_Crime_4, BS_TR_Crime_5), ~ recode(., 
      `10` = 0, `9` = 1, `8` = 2, `7` = 3, `6` = 4, `4` = 6, `3` = 7, `2` = 8, `1` = 9, `0` = 10)), ##Thought-Rating
    
    across(c(self_esteem_2, self_esteem_5, self_esteem_6, self_esteem_8, self_esteem_9), ~ recode(., 
      `1` = 4, `11` = 3, `12` = 2, `13` = 1)), ##Rosenberg Self-esteem Scale

    across(c(self_esteem_1, self_esteem_3, self_esteem_4, self_esteem_7, self_esteem_10), ~ recode(., 
      `1` = 1, `11` = 2, `12` = 3, `13` = 4)), ##Rosenberg Self-esteem Scale
    
    across(c(ncog3, ncog4, ncog5, ncog7, ncog8, ncog9, ncog12, ncog16, ncog17), ~ recode(., 
      `1` = 5, `2` = 4, `4` = 2, `5` = 1)), ##Need for Cognition
    
    across(c(DTS_Nar_2, DTS_Nar_6, DTS_Nar_8, DTS_Path_2, DTS_Path_7), ~ recode(., 
      `1` = 5, `2` = 4, `4` = 2, `5` = 1)), ##The Short Dark Triad
    
    across(c(NPI_1, NPI_2, NPI_3, NPI_4, NPI_5, NPI_6, NPI_7, NPI_8, NPI_9, NPI_10, NPI_11, NPI_12, NPI_13, NPI_14, NPI_15, NPI_16), ~ recode(., 
      `1` = 2, `2` = 1)), ##Narcissistic Personality Inventory–16
    
    across(c(A4CTS_1, A4CTS_2, A4CTS_3, A4CTS_4, A4CTS_5, A4CTS_6, A4CTS_19, A4CTS_20, A4CTS_21, A4CTS_22, A4CTS_23, A4CTS_24), ~ recode(.,
      `1` = 6, `2` = 5, `3` = 4, `4` = 3, `5` = 2, `6` = 1)), ##4-Component Thinking Styles Questionnaire
    
    across(c(LSRP_SPS_3, LSRP_SPS_7, LSRP_PPS_10, LSRP_PPS_12, LSRP_PPS_14, LSRP_PPS_16), ~ recode(.,
      `1` = 4, `2` = 3, `3` = 2, `4` = 1)), ##Levenson Self-Report Psychopathy Scale
   
    across(c(aopen3, aopen4, aopen5, aopen7, aopen8), ~ recode(.,
      `1` = 6, `3` = 5, `4` = 4, `5` = 3, `6` = 2, `7` = 1)), ##Actively Open-Minded Thinking about Evidence Scale
    across(c(aopen1, aopen2, aopen6), ~ recode(.,
      `1` = 1, `3` = 2, `4` = 3, `5` = 4, `6` = 5, `7` = 6)),
    
    across(c(nclos2, nclos5, nclos15, nclos12, nclos17, nclos18, nclos19, nclos20, nclos22, nclos24, nclos27, nclos28, nclos34, nclos37, nclos38, nclos42), ~ recode(.,
      `1` = 6, `2` = 5, `3` = 4, `4` = 3, `5` = 2, `6` = 1)), ##Need for closure
    
    across(c(hex1, hex9, hex10, hex12, hex14, hex15, hex19, hex20, hex21, hex24, hex26, hex28, hex30, hex31, hex32, hex35, hex41, hex44, hex46, hex48, hex49, hex52, hex53, hex55, hex56, hex57, hex59, hex60), ~ recode(.,
      `1` = 5, `2` = 4, `4` = 2, `5` = 1)) ##HEXACO
    )

```
I realized that I should have create new variables for the recoded ones, so that would be easier for me to keep track on if the numbers are already recoded. I had too many variables this time so I did not do that. 

## Step 3: calculating scales that requires more than sum or mean
```{r BS Thought rating and listing measurement calculation}
## For the thought listing and rating task, I need to first identify participants' valid responses. I coded 1 for all valid responses and 0 for all the invalid ones. The criteria is that if the participant answered NA, not sure, or answers suggesting they do not have answers, I code it as 0. I created variables such as CG_score, RC_score, and CR_score for each question. I verify all of the thought rating scores by sliding the thought rating variables next to their respective thought scores (e.g., “thought_rating1” should be next to “thought1_score”)
## How to compute: I Sum the total number of thoughts for each participant per the topic. In other words, if a participant wrote three valid thoughts for topic 1, they should have “3” for their “sum_recoded_TR_topic”.

Thesis_scale <- Thesis_scale %>%
  mutate(
    recoded_college = rowSums(select(., CG1_score, CG2_score, CG3_score, CG4_score, CG5_score), na.rm = TRUE),
    recoded_recycling = rowSums(select(., RC1_score, RC2_score, RC3_score, RC4_score, RC5_score), na.rm = TRUE),
    recoded_crime = rowSums(select(., CR1_score, CR2_score, CR3_score, CR4_score, CR5_score), na.rm = TRUE),
    )

## Next, I need to delete the scores in the BS_TR_topic items if I marked "0" in the accordingly topic_score variables. In other words, I need to put "0" in the BS_TR_topic when the participant did not provide valid answers.
##topic: college graduate
Thesis_scale$BS_TR_CG_1 <- ifelse(Thesis_scale$CG1_score == 0, 0, Thesis_scale$BS_TR_CG_1)
Thesis_scale$BS_TR_CG_2 <- ifelse(Thesis_scale$CG2_score == 0, 0, Thesis_scale$BS_TR_CG_2)
Thesis_scale$BS_TR_CG_3 <- ifelse(Thesis_scale$CG3_score == 0, 0, Thesis_scale$BS_TR_CG_3)
Thesis_scale$BS_TR_CG_4 <- ifelse(Thesis_scale$CG4_score == 0, 0, Thesis_scale$BS_TR_CG_4)
Thesis_scale$BS_TR_CG_5 <- ifelse(Thesis_scale$CG5_score == 0, 0, Thesis_scale$BS_TR_CG_5)
##topic: recycling
Thesis_scale$BS_TR_Recylcing_1 <- ifelse(Thesis_scale$RC1_score == 0, 0, Thesis_scale$BS_TR_Recylcing_1)
Thesis_scale$BS_TR_Recylcing_2 <- ifelse(Thesis_scale$RC2_score == 0, 0, Thesis_scale$BS_TR_Recylcing_2)
Thesis_scale$BS_TR_Recylcing_3 <- ifelse(Thesis_scale$RC3_score == 0, 0, Thesis_scale$BS_TR_Recylcing_3)
Thesis_scale$BS_TR_Recylcing_4 <- ifelse(Thesis_scale$RC4_score == 0, 0, Thesis_scale$BS_TR_Recylcing_4)
Thesis_scale$BS_TR_Recylcing_5 <- ifelse(Thesis_scale$RC5_score == 0, 0, Thesis_scale$BS_TR_Recylcing_5)
##topic: retruning to crime after prison
Thesis_scale$BS_TR_Crime_1 <- ifelse(Thesis_scale$CR1_score == 0, 0, Thesis_scale$BS_TR_Crime_1)
Thesis_scale$BS_TR_Crime_2 <- ifelse(Thesis_scale$CR2_score == 0, 0, Thesis_scale$BS_TR_Crime_2)
Thesis_scale$BS_TR_Crime_3 <- ifelse(Thesis_scale$CR3_score == 0, 0, Thesis_scale$BS_TR_Crime_3)
Thesis_scale$BS_TR_Crime_4 <- ifelse(Thesis_scale$CR4_score == 0, 0, Thesis_scale$BS_TR_Crime_4)
Thesis_scale$BS_TR_Crime_5 <- ifelse(Thesis_scale$CR5_score == 0, 0, Thesis_scale$BS_TR_Crime_5)
## Next, I sum the recoded_TR_topic variables separately for each topic. If the participants wrote about five answers, they should all have five “sum_recoded_TR_topic” scores (one for each topic).
Thesis_scale <- Thesis_scale %>%
  mutate(
    sum_recoded_TR_college = rowSums(select(., BS_TR_CG_1, BS_TR_CG_2, BS_TR_CG_3, BS_TR_CG_4, BS_TR_CG_5), na.rm = TRUE),
    sum_recoded_TR_recycling = rowSums(select(., BS_TR_Recylcing_1, BS_TR_Recylcing_2, BS_TR_Recylcing_3, BS_TR_Recylcing_4, BS_TR_Recylcing_5), na.rm = TRUE),
    sum_recoded_TR_crime = rowSums(select(., BS_TR_Crime_1, BS_TR_Crime_2, BS_TR_Crime_3, BS_TR_Crime_4, BS_TR_Crime_5), na.rm = TRUE)
    )
###I als0 just want to double check what does na.rm did for my data in terms of na.rm = TRUE/FALSE
length(Thesis_scale$recoded_college)

## Lastly, I use this equation to calculate the BS Proportion per topic, whereby each participant will have five individual BS Proportion scores (one for each topic): sum_recoded_thought_rating_topic1 / (sum thought_frequency_topic1 x 10)
Thesis_scale <- Thesis_scale %>%
  mutate(BSthought = sum_recoded_TR_college / (recoded_college * 10))

# Check if it worked
head(Thesis_scale$BSthought)

TOO MANY NAs, what can I do with this?
```

```{r}
colnames(Thesis_scale)
Thesis_scale$BFS_score <- Thesis_scale %>% 
  rowMeans(BFS_1:BFS_12)
psych::describe(Thesis_scale$BFS_score)
```


```{r computing mean, sd, and other descriptives for each scales and variables}
##Define the scales
##Bullshit Frequency scale general  
bfs <- c("BFS_1", "BFS_2", "BFS_3", "BFS_4", "BFS_5", "BFS_6", "BFS_7", "BFS_8", "BFS_9", "BFS_10", "BFS_11", "BFS_12")
##Bullshit Frequency scale evasive
bfse <- c("BFS_9", "BFS_10", "BFS_11", "BFS_12")
##Bullshit Frequency scale persuasive
bfsp <- c("BFS_1", "BFS_2", "BFS_3", "BFS_4", "BFS_5", "BFS_6", "BFS_7", "BFS_8")
##Bullshit Propensity scale 
bps <- c("BPS_1", "BPS_2", "BPS_3", "BPS_4", "BPS_5", "BPS_6", "BPS_7", "BPS_8", "BPS_9", "BPS_10", "BPS_11", "BPS_12")
##Lying in Everyday Situations Scale
lie <- c("lies1", "lies2", "lies3", "lies4", "lies5", "lies6", "lies7", "lies8", "lies9", "lies10", "lies11", "lies12", "lies13", "lies14")
##Short_dark_triad Narcissism
sdtnarc <- c("DTS_Nar_1", "DTS_Nar_2", "DTS_Nar_3", "DTS_Nar_4", "DTS_Nar_5", "DTS_Nar_6", "DTS_Nar_7", "DTS_Nar_8", "DTS_Nar_9")
##Short_dark_triad Machiavellianism
sdtmach <- c("DTS_MACH_1", "DTS_MACH_2", "DTS_MACH_3", "DTS_MACH_4", "DTS_MACH_5", "DTS_MACH_6", "DTS_MACH_7", "DTS_MACH_8", "DTS_MACH_9")
##Short_dark_triad Psychopathy
sdtpsych <- c("DTS_Path_1", "DTS_Path_2", "DTS_Path_3", "DTS_Path_4", "DTS_Path_5", "DTS_Path_6", "DTS_Path_7", "DTS_Path_8", "DTS_Path_9")
##Machiavellianism Personality scale
machi <- c("MPS_1", "MPS_2", "MPS_3", "MPS_4", "MPS_5", "MPS_6", "MPS_7", "MPS_8", "MPS_9", "MPS_10", "MPS_11", "MPS_12", "MPS_13", "MPS_14", "MPS_15", "MPS_16")
##Levenson Self-Report Psychopathy Scale
psycho <- c("LSRP_PPS_1", "LSRP_PPS_2", "LSRP_PPS_3", "LSRP_PPS_4", "LSRP_PPS_5", "LSRP_PPS_6", "LSRP_PPS_7", "LSRP_PPS_8", "LSRP_PPS_9", "LSRP_PPS_10", "LSRP_PPS_11", "LSRP_PPS_12", "LSRP_PPS_13", "LSRP_PPS_14", "LSRP_PPS_15", "LSRP_PPS_16", "LSRP_SPS_1", "LSRP_SPS_2", "LSRP_SPS_3", "LSRP_SPS_4", "LSRP_SPS_5", "LSRP_SPS_6", "LSRP_SPS_7", "LSRP_SPS_8", "LSRP_SPS_9", "LSRP_SPS_10")
##primary factor of psychopathy scale
psychopri <- c("LSRP_PPS_1", "LSRP_PPS_2", "LSRP_PPS_3", "LSRP_PPS_4", "LSRP_PPS_5", 
                    "LSRP_PPS_6", "LSRP_PPS_7", "LSRP_PPS_8", "LSRP_PPS_9", "LSRP_PPS_10", 
                    "LSRP_PPS_11", "LSRP_PPS_12", "LSRP_PPS_13", "LSRP_PPS_14", "LSRP_PPS_15", 
                    "LSRP_PPS_16")
##secondary factor of psychopathy scale
psychosec <- c("LSRP_SPS_1", "LSRP_SPS_2", "LSRP_SPS_3", "LSRP_SPS_4", "LSRP_SPS_5", 
                    "LSRP_SPS_6", "LSRP_SPS_7", "LSRP_SPS_8", "LSRP_SPS_9", "LSRP_SPS_10")
##Self-esteem (Rosenberg)
se <- c("self_esteem_1", "self_esteem_2", "self_esteem_3", "self_esteem_4", "self_esteem_5", 
                     "self_esteem_6", "self_esteem_7", "self_esteem_8", "self_esteem_9", "self_esteem_10")
##HEXACO
##Honesty_humility
hon <- c("hex6", "hex12", "hex18", "hex24", "hex30", "hex36", "hex42", "hex48", "hex54", "hex60")
##Emotionality
emo <- c("hex5", "hex11", "hex17", "hex23", "hex29", "hex35", "hex41", "hex47", "hex53", "hex59")
##Extraversion
extra <- c("hex4", "hex10", "hex16", "hex22", "hex28", "hex34", "hex40", "hex46", "hex52", "hex58")
##Agreeableness
agree <- c("hex3", "hex9", "hex15", "hex21", "hex27", "hex33", "hex39", "hex45", "hex51", "hex57")
##CONSCIENTIOUSNESS
cons <- c("hex2", "hex8", "hex14", "hex20", "hex26", "hex32", "hex38", "hex44", "hex50", "hex56")
##Openness to Experience
open <- c("hex1", "hex7", "hex13", "hex19", "hex25", "hex31", "hex37", "hex43", "hex49", "hex55")
##Intellectual Humility Scale
ihs <- c("IHS_1", "IHS_2", "IHS_3", "IHS_4", "IHS_5", "IHS_6")
##Need for Closure
nclos <- c("nclos1", "nclos2", "nclos3", "nclos4", "nclos5", "nclos6", "nclos7", "nclos8", "nclos9", "nclos10", 
                                                 "nclos11", "nclos12", "nclos13", "nclos14", "nclos15", 
                                                 "nclos16", "nclos17", "nclos18", "nclos19", "nclos20", 
                                                 "nclos21", "nclos22", "nclos23", "nclos24", "nclos25", 
                                                 "nclos26", "nclos27", "nclos28", "nclos29", "nclos30", 
                                                 "nclos31", "nclos32", "nclos33", "nclos34", "nclos35", 
                                                 "nclos36", "nclos37", "nclos38", "nclos39", "nclos40", 
                                                 "nclos41", "nclos42")
##Need for Cognition
ncog <- c("ncog7", "ncog8", "ncog9", "ncog10", "ncog11", "ncog12", 
                                               "ncog13", "ncog14", "ncog15", "ncog16", "ncog17", "ncog18")
##Actively Open Thinking Style
openTS <- c("A4CTS_1", "A4CTS_2", "A4CTS_3", "A4CTS_4", "A4CTS_5", "A4CTS_6")
##Close-minded Thinking Style
closeTS <- c("A4CTS_7", "A4CTS_8", "A4CTS_9", "A4CTS_10", "A4CTS_11", "A4CTS_12")
##prefer intuitive Thinking Style
intuitiveTS <- c("A4CTS_13", "A4CTS_14", "A4CTS_15", "A4CTS_16", "A4CTS_17", "A4CTS_18")
##prefer effortful Thinking Style
effortTS <- c("A4CTS_19", "A4CTS_20", "A4CTS_21", "A4CTS_22", "A4CTS_23", "A4CTS_24")
##Actively Open-Minded Thinking about Evidence Scale 
Activeopen <- c("aopen1", "aopen2", "aopen3", "aopen4", "aopen5", "aopen6", "aopen7", "aopen8")
##Faith in Intuition Scale
fi <- c("fi1", "fi2", "fi3", "fi4", "fi5", "fi6", "fi7", "fi8", "fi9", "fi10", "fi11", "fi12")
```

```{r computing mean, sd, and other descriptives for each scales and variables}
colnames(Thesis_clean)
Thesis_clean$BFS_score <- Thesis_clean %>% 
  rowMeans(BFS_1:BFS_12)
psych::describe(Thesis_clean$BFS_score)

df %>% 
  psych::describe(var1, var2, ...)


Thesis_scale$BS_TR_CG_3_r <- ifelse(Thesis_scale$CG3_score == 0, 0, Thesis_scale$BS_TR_CG_3)
```


```{r mean for each scale}
Thesis_scale <- Thesis_scale %>%
  mutate(
    bfsmean = rowMeans(select(., all_of(bfs)), na.rm = TRUE),
    bfsemean = rowMeans(select(., all_of(bfse)), na.rm = TRUE),
    bfspmean = rowMeans(select(., all_of(bfsp)), na.rm = TRUE),
    bpsmean = rowMeans(select(., all_of(bps)), na.rm = TRUE),
    liemean = rowMeans(select(., all_of(lie)), na.rm = TRUE),
    sdtnarcmean = rowMeans(select(., all_of(sdtnarc)), na.rm = TRUE),
    sdtmachmean = rowMeans(select(., all_of(sdtmach)), na.rm = TRUE),
    sdtpsychmean = rowMeans(select(., all_of(sdtpsych)), na.rm = TRUE),
    machimean = rowMeans(select(., all_of(machi)), na.rm = TRUE),
    psychomean = rowMeans(select(., all_of(psycho)), na.rm = TRUE),
    psychoprimean = rowMeans(select(., all_of(psychopri)), na.rm = TRUE),
    psychosecmean = rowMeans(select(., all_of(psychosec)), na.rm = TRUE),
    semean = rowMeans(select(., all_of(se)), na.rm = TRUE),
    honmean = rowMeans(select(., all_of(hon)), na.rm = TRUE),
    emomena = rowMeans(select(., all_of(emo)), na.rm = TRUE),
    extramean = rowMeans(select(., all_of(extra)), na.rm = TRUE),
    agreemean = rowMeans(select(., all_of(agree)), na.rm = TRUE),
    consmean = rowMeans(select(., all_of(cons)), na.rm = TRUE),
    openmean = rowMeans(select(., all_of(open)), na.rm = TRUE),
    ihsmean = rowMeans(select(., all_of(ihs)), na.rm = TRUE),
    nclosmean = rowMeans(select(., all_of(nclos)), na.rm = TRUE),
    ncogmean = rowMeans(select(., all_of(ncog)), na.rm = TRUE),
    openTSmean = rowMeans(select(., all_of(openTS)), na.rm = TRUE),
    closeTSmean = rowMeans(select(., all_of(closeTS)), na.rm = TRUE),
    intuitiveTSmean = rowMeans(select(., all_of(intuitiveTS)), na.rm = TRUE),
    effortTSmean = rowMeans(select(., all_of(effortTS)), na.rm = TRUE),
    Activeopenmean = rowMeans(select(., all_of(Activeopen)), na.rm = TRUE),
    fimean = rowMeans(select(., all_of(fi)), na.rm = TRUE)
  )

```

```{r}
##BFS and BPS
partial_BFSBPS <- Thesis_scale %>% 
  select(bfsmean, bpsmean, liemean) %>%
  drop_na()

partial_BFSBPS_result <- pcor.test(partial_BFSBPS$bfsmean, 
                                 partial_BFSBPS$bpsmean, 
                                 partial_BFSBPS$liemean)

print(partial_corr_result)

##BFS and mach
partial_BFSmach<- Thesis_scale %>% 
  select(bfsmean, sdtmachmean, liemean) %>% 
  drop_na()

partial_BFSmach_result <- pcor.test(partial_BFSmach$bfsmean, 
                                 partial_BFSmach$sdtmachmean, 
                                 partial_BFSmach$liemean)

print(partial_BFSmach_result)

##BFS and narc
partial_BFSnarc<- Thesis_scale %>% 
  select(bfsmean, sdtnarcmean, liemean) %>% 
  drop_na()

partial_BFSnarc_result <- pcor.test(
  x = partial_BFSnarc$bfsmean,
  y = partial_BFSnarc$sdtnarcmean,
  z = partial_BFSnarc$liemean)

print(partial_BFSnarc_result)

##BFS and psychopathy
partial_BFSpsych<- Thesis_scale %>% 
  select(bfsmean, sdtpsychmean, liemean) %>%
  drop_na()

partial_BFSpsych_result <- pcor.test(
  x = partial_BFSpsych$bfsmean,
  y = partial_BFSpsych$sdtpsychmean,
  z = partial_BFSpsych$liemean
  )

print(partial_BFSpsych_result)

##BPS and mach
partial_BPSmach<- Thesis_scale %>% 
  select(bpsmean, sdtmachmean, liemean) %>%
  drop_na()

partial_BPSmach_result <- pcor.test(
  x = partial_BPSmach$bpsmean,
  y = partial_BPSmach$sdtmachmean,
  z = partial_BPSmach$liemean
  )

print(partial_BPSmach_result)

##BPS and narc
partial_BPSnarc<- Thesis_scale %>% 
  select(bpsmean, sdtnarcmean, liemean) %>%
  drop_na()

partial_BPSnarc_result <- pcor.test(
  x = partial_BPSnarc$bpsmean,
  y = partial_BPSnarc$sdtnarcmean,
  z = partial_BPSnarc$liemean
  )

print(partial_BPSnarc_result)

##BPS and psychopathy
partial_BPSpsych<- Thesis_scale %>% 
  select(bpsmean, sdtpsychmean, liemean) %>%
  drop_na()

partial_BPSpsych_result <- pcor.test(
  x = partial_BPSpsych$bpsmean,
  y = partial_BPSpsych$sdtpsychmean,
  z = partial_BPSpsych$liemean
  )

print(partial_BPSpsych_result)

```
```{r}
percentage correct
```






